// Auth
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

// Admin
export const VERIFY_FUNDRAISER = 'VERIFY_FUNDRAISER';
export const VERIFY_PROGRAM = 'VERIFY_PROGRAM';

// User
export const FETCH_USER_WALLET_INFO = 'FETCH_USER_WALLET_INFO';
export const FETCH_USER_DONATION_HISTORY = 'FETCH_USER_DONATION_HISTORY';

// Program
export const FETCH_PROGRAM_LIST = 'FETCH_PROGRAM_LIST';
export const FETCH_PROGRAM_DETAIL = 'FETCH_PROGRAM_DETAIL';
export const DONATE_DONATION_PROGRAM = 'DONATE_DONATION_PROGRAM';
export const CREATE_DONATION_PROGRAM = 'CREATE_DONATION_PROGRAM';