// Auth
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const CLEAR_EDIT_USER_RESPONSE = 'CLEAR_EDIT_USER_RESPONSE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CLEAR_CHANGE_PASSWORD_RESPONSE = 'CLEAR_CHANGE_PASSWORD_RESPONSE';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR';

export const CLEAR_AUTH_RESPONSE = 'CLEAR_AUTH_RESPONSE';

// Admin
export const VERIFY_FUNDRAISER = 'VERIFY_FUNDRAISER';
export const VERIFY_FUNDRAISER_SUCCESS = 'VERIFY_FUNDRAISER_SUCCESS';
export const VERIFY_FUNDRAISER_ERROR = 'VERIFY_FUNDRAISER_ERROR';
export const CLEAR_VERIFY_FUNDRAISER_RESPONSE = 'CLEAR_VERIFY_FUNDRAISER_RESPONSE';

export const FETCH_PENDING_FUNDRAISER = 'FETCH_PENDING_FUNDRAISER';
export const FETCH_PENDING_FUNDRAISER_SUCCESS = 'FETCH_PENDING_FUNDRAISER_SUCCESS';
export const FETCH_PENDING_FUNDRAISER_ERROR = 'FETCH_PENDING_FUNDRAISER_ERROR';

export const VERIFY_PROGRAM = 'VERIFY_PROGRAM';
export const VERIFY_PROGRAM_SUCCESS = 'VERIFY_PROGRAM_SUCCESS';
export const VERIFY_PROGRAM_ERROR = 'VERIFY_PROGRAM_ERROR';
export const CLEAR_VERIFY_PROGRAM_RESPONSE = 'CLEAR_VERIFY_PROGRAM_RESPONSE';

export const FETCH_PENDING_PROGRAM = 'FETCH_PENDING_PROGRAM';
export const FETCH_PENDING_PROGRAM_SUCCESS = 'FETCH_PENDING_PROGRAM_SUCCESS';
export const FETCH_PENDING_PROGRAM_ERROR = 'FETCH_PENDING_PROGRAM_ERROR';

export const VERIFY_WITHDRAWAL = 'VERIFY_WITHDRAWAL';
export const VERIFY_WITHDRAWAL_SUCCESS = 'VERIFY_WITHDRAWAL_SUCCESS';
export const VERIFY_WITHDRAWAL_ERROR = 'VERIFY_WITHDRAWAL_ERROR';
export const CLEAR_VERIFY_WITHDRAWAL_RESPONSE = 'CLEAR_VERIFY_WITHDRAWAL_RESPONSE';

export const FETCH_PENDING_WITHDRAWAL = 'FETCH_PENDING_WITHDRAWAL';
export const FETCH_PENDING_WITHDRAWAL_SUCCESS = 'FETCH_PENDING_WITHDRAWAL_SUCCESS';
export const FETCH_PENDING_WITHDRAWAL_ERROR = 'FETCH_PENDING_WITHDRAWAL_ERROR';

// User
export const FETCH_USER_WALLET_INFO = 'FETCH_USER_WALLET_INFO';
export const FETCH_USER_WALLET_INFO_SUCCESS = 'FETCH_USER_WALLET_INFO_SUCCESS';
export const FETCH_USER_WALLET_INFO_ERROR = 'FETCH_USER_WALLET_INFO_ERROR';

export const FETCH_USER_WALLET_HISTORY = 'FETCH_USER_WALLET_HISTORY';
export const FETCH_USER_WALLET_HISTORY_SUCCESS = 'FETCH_USER_WALLET_HISTORY_SUCCESS';
export const FETCH_USER_WALLET_HISTORY_ERROR = 'FETCH_USER_WALLET_HISTORY_ERROR';

export const FETCH_USER_DONATION_HISTORY = 'FETCH_USER_DONATION_HISTORY';
export const FETCH_USER_DONATION_HISTORY_SUCCESS = 'FETCH_USER_DONATION_HISTORY_SUCCESS';
export const FETCH_USER_DONATION_HISTORY_ERROR = 'FETCH_USER_DONATION_HISTORY_ERROR';

export const TOPUP_USER_WALLET = 'TOPUP_USER_WALLET';
export const TOPUP_USER_WALLET_SUCCESS = 'TOPUP_USER_WALLET_SUCCESS';
export const TOPUP_USER_WALLET_ERROR = 'TOPUP_USER_WALLET_ERROR';
export const CLEAR_TOPUP_USER_WALLET_RESPONSE = 'CLEAR_TOPUP_USER_WALLET_RESPONSE';

// Program
export const SEARCH_DONATION_PROGRAM = 'SEARCH_DONATION_PROGRAM';
export const SEARCH_DONATION_PROGRAM_SUCCESS = 'SEARCH_DONATION_PROGRAM_SUCCESS';
export const SEARCH_DONATION_PROGRAM_ERROR = 'SEARCH_DONATION_PROGRAM_ERROR';
export const CLEAR_SEARCH_DONATION_PROGRAM = 'CLEAR_SEARCH_DONATION_PROGRAM';

export const FETCH_PROGRAM_LIST = 'FETCH_PROGRAM_LIST';
export const FETCH_PROGRAM_LIST_SUCCESS = 'FETCH_PROGRAM_LIST_SUCCESS';
export const FETCH_PROGRAM_LIST_ERROR = 'FETCH_PROGRAM_LIST_ERROR';

export const FETCH_PROGRAM_DETAIL = 'FETCH_PROGRAM_DETAIL';
export const FETCH_PROGRAM_DETAIL_SUCCESS = 'FETCH_PROGRAM_DETAIL_SUCCESS';
export const FETCH_PROGRAM_DETAIL_ERROR = 'FETCH_PROGRAM_DETAIL_ERROR';
export const CLEAR_FETCH_PROGRAM_DETAIL = 'CLEAR_FETCH_PROGRAM_DETAIL';

export const DONATE_DONATION_PROGRAM = 'DONATE_DONATION_PROGRAM';
export const DONATE_DONATION_PROGRAM_SUCCESS = 'DONATE_DONATION_PROGRAM_SUCCESS';
export const DONATE_DONATION_PROGRAM_ERROR = 'DONATE_DONATION_PROGRAM_ERROR';
export const CLEAR_DONATE_DONATION_PROGRAM_RESPONSE = 'CLEAR_DONATE_DONATION_PROGRAM_RESPONSE';

// Fundraiser
export const CREATE_DONATION_PROGRAM = 'CREATE_DONATION_PROGRAM';
export const CREATE_DONATION_PROGRAM_SUCCESS = 'CREATE_DONATION_PROGRAM_SUCCESS';
export const CREATE_DONATION_PROGRAM_ERROR = 'CREATE_DONATION_PROGRAM_ERROR';
export const CLEAR_CREATE_DONATION_PROGRAM_RESPONSE = 'CLEAR_CREATE_DONATION_PROGRAM_RESPONSE';

export const FETCH_ALL_FUNDRAISER_PROGRAM = 'FETCH_ALL_FUNDRAISER_PROGRAM';
export const FETCH_ALL_FUNDRAISER_PROGRAM_SUCCESS = 'FETCH_ALL_FUNDRAISER_PROGRAM_SUCCESS';
export const FETCH_ALL_FUNDRAISER_PROGRAM_ERROR = 'FETCH_ALL_FUNDRAISER_PROGRAM_ERROR';

export const CREATE_PROGRAM_WITHDRAWAL_REQUEST = 'CREATE_PROGRAM_WITHDRAWAL_REQUEST';
export const CREATE_PROGRAM_WITHDRAWAL_REQUEST_SUCCESS = 'CREATE_PROGRAM_WITHDRAWAL_REQUEST_SUCCESS';
export const CREATE_PROGRAM_WITHDRAWAL_REQUEST_ERROR = 'CREATE_PROGRAM_WITHDRAWAL_REQUEST_ERROR';
export const CLEAR_CREATE_PROGRAM_WITHDRAWAL_REQUEST_RESPONSE = 'CLEAR_CREATE_PROGRAM_WITHDRAWAL_REQUEST_RESPONSE';