name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Layer Cache Docker
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build Docker Image
        run: docker build . --file ./Dockerfile --tag seacf-fe

      - name: Output and Compress Docker Image
        run: |
          docker save seacf-fe | gzip > seacf-fe.tar.gz

      - name: Elevate Permission
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            sudo chmod -R 777 /var/opt

      - name: Push Docker Image
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "seacf-fe.tar.gz"
          target: "/var/opt/"

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/opt/
            sudo docker load -i seacf-fe.tar.gz
            sudo docker run -d -p 3337:80 seacf-fe
            sudo chmod -R 755 /var/opt

      - name: Remove Docker Image
        if: always()
        run: |
          rm -rf seacf-fe.tar.gz
            
